AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Multi-language image description API with text and audio output

Globals:
  Function:
    Timeout: 60
    MemorySize: 1024
    Runtime: python3.9
  Api:
    Cors:
      AllowMethods: "'GET,POST,OPTIONS'"
      AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
      AllowOrigin: "'*'"

Resources:
  ImageDescriptionFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Policies:
        - Statement:
          - Effect: Allow
            Action:
              - bedrock:InvokeModel
            Resource: '*'
          - Effect: Allow
            Action:
              - polly:SynthesizeSpeech
            Resource: '*'
      Events:
        TextDescription:
          Type: Api
          Properties:
            Path: /describe/text
            Method: post
        AudioDescription:
          Type: Api
          Properties:
            Path: /describe/audio
            Method: post

Outputs:
  ApiEndpoint:
    Description: API Gateway endpoint URL for Prod stage
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"
    
  TextDescriptionEndpoint:
    Description: Text description endpoint
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/describe/text"
    
  AudioDescriptionEndpoint:
    Description: Audio description endpoint
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/describe/audio"
